export const client = {
  name: "sample",
  tagline: "Professional landscaping services in Irvine",
  phone: "(949) 123-4567",
  email: "john@sample.com",
  address: "123 Main St",
  city: "Irvine",
  state: "CA",
  serviceArea: ["Irvine","Newport Beach","Laguna Hills","Mission Viejo"],
  primaryColor: "#2d5a3d",
  industry: "landscaping",
  services: ["Lawn care","Garden design","Irrigation","Tree trimming","Mulching","Sod installation","Leaf removal"],
  cmsUrl: "https://cms.sebvia.com",
  tenantSlug: "sample",
  googleAnalyticsId: '',
  domain: "sample.sebvia.com",
};
